services:
  face-detection-app:
    container_name: backend_camera
    build: .
    networks:
      - SY_network
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    devices:
      - "/dev/video0:/dev/video0"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis_cache   # ชื่อ container ของ Redis จาก backend 1
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=mydatabase

networks:
  SY_network:
    external: true
